version: '3.0'

services:
  mysql:
    image: mysql:8.0-bookworm
    container_name: mysql-spring-assisted
    environment:
      - MYSQL_ROOT_PASSWORD=supersecretpasword
      - MYSQL_DATABASE=spring-blog-db
    ports:
      - "3306:3306"
    extra_hosts:
      - "host.docker.internal:host-gateway" ## Docker
    ##  - "host.containers.internal:host-gateway" ## Podman
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p$$MYSQL_ROOT_PASSWORD"]
      interval: 30s
      timeout: 30s
      retries: 10
      start_period: 40s

  spring-blog:
    build: .
    container_name: spring-blog
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql-spring-assisted:3306/spring-blog-db
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=supersecretpasword
    depends_on:
      mysql:
        condition: service_healthy