version: '3.0'

services:
#  mysql:
#    image: mysql:8.0-bookworm
#    container_name: mysql-spring-assisted
#    environment:
#      - MYSQL_ROOT_PASSWORD=supersecretpasword
#      - MYSQL_DATABASE=spring-blog-db
#    ports:
#      - "3306:3306"
#    extra_hosts:
#      - "host.docker.internal:host-gateway" ## Docker
#    ##  - "host.containers.internal:host-gateway" ## Podman
#    healthcheck:
#      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p$$MYSQL_ROOT_PASSWORD"]
#      interval: 30s
#      timeout: 30s
#      retries: 10
#      start_period: 40s

  spring-deploy-student6-app:
    build:
      context: .
      dockerfile: Dockerfile
    image: ${DOCKERHUB_USERNAME}/spring-deploy-student6-app:latest
    container_name: spring-deploy-student6-app
    ports:
      - "${APP_PORT:-9006}:${APP_PORT:-9006}"
    env_file:
      - .env
    environment:
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - APP_PORT=${APP_PORT:-9006}
      - SPRING_PROFILES_ACTIVE=${SPRING_PROFILES_ACTIVE:-dev}
    networks:
      - classroom_classroom_net
    restart: always

networks:
  classroom_classroom_net:
    external: true