spring:
    application:
        name: spring-asissted
#    Use this if to run this app locally
#    datasource:
#        url: jdbc:mysql://localhost:3306/spring-blog-db
#        username: root
#        password: supersecretpassword  
#        driver-class-name: com.mysql.cj.jdbc.Driver
    jpa:
        hibernate:
            ddl-auto: update
        show-sql: true
        properties:
            hibernate:
                dialect: org.hibernate.dialect.MySQLDialect
    security:
        user:
            name: admin
            password: password
jwt:
    secret: "v6yB8p98p9zB6X5y8p9zB6X5y8p9zB6X5y8p9zB6X5y8p9zB6X5y8p9zB6X5y8p9zB6X5y8p9zB6X5y8p"
    expiration: 86400000 # 24 hours

